// Auto-generated by scripts/generate-banner.mjs — do not edit manually
import chalk from 'chalk';

// Contrast-boosted palette (1.2x from midpoint, green zeroed for pure magenta)
const P: [number, number, number][] = [[205,0,176],[176,0,176],[255,0,205],[234,0,205],[234,0,176],[147,0,176],[176,0,205],[147,0,147],[118,0,147],[118,0,147],[61,0,118],[90,0,147],[90,0,118],[176,0,176],[118,0,176]];
const D = [
  '..........00..........................',
  '........110000........................',
  '.......11...000.......................',
  '......11.0233.044.....................',
  '.....11.5643233.444...................',
  '.....115551343230.34..................',
  '....11515550344327.234................',
  '...11.1155181344339a.234..............',
  '..51.111115bb044430bba.244............',
  '..5.1111119bb9444447b9ba234...........',
  '.551111119bbbb7404449cbbc.233.........',
  '55.111117bbbbbb1000009bb9ba.33........',
  '5.001001bbbbbbb9000001bbbb9..3........',
  '5.000001bbbbbbbb100001bbbbbb.3........',
  '5.030001bbbbbbbb111105bbbb9c.3........',
  '55.400047bbbbbb7111119bbbbc.33........',
  '.553344449bbbb9111119bb9c.234.........',
  '..5.3344409bb9111117b9ba.344..........',
  '..11.334430bb5111159ba.244............',
  '...11.33443d8155519a.234..............',
  '....15223330555519.234................',
  '.....1.2230555558.344.................',
  '.....11.225e55e.444...................',
  '......11.155e.444.....................',
  '.......11...000.......................',
  '........110000........................',
  '.........100..........................',
  '......................................',
];

const IDX: Record<string, number> = {};
'0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('').forEach((c, i) => { IDX[c] = i; });

function decodeIdx(c: string): number {
  return c === '.' ? -1 : IDX[c];
}

export function renderBanner(): string {
  const lines: string[] = [];
  for (let y = 0; y < D.length; y += 2) {
    let line = '';
    const topRow = D[y];
    const botRow = D[y + 1];
    for (let x = 0; x < topRow.length; x++) {
      const ti = decodeIdx(topRow[x]);
      const bi = decodeIdx(botRow[x]);
      if (ti === -1 && bi === -1) {
        line += ' ';
      } else if (ti >= 0 && bi === -1) {
        const [r, g, b] = P[ti];
        line += chalk.rgb(r, g, b)('\u2580');
      } else if (ti === -1 && bi >= 0) {
        const [r, g, b] = P[bi];
        line += chalk.rgb(r, g, b)('\u2584');
      } else {
        const [tr, tg, tb] = P[ti];
        const [br, bg, bb] = P[bi];
        if (tr === br && tg === bg && tb === bb) {
          line += chalk.rgb(tr, tg, tb)('\u2588');
        } else {
          line += chalk.rgb(tr, tg, tb).bgRgb(br, bg, bb)('\u2580');
        }
      }
    }
    lines.push('    ' + line);
  }
  return lines.join('\n');
}
