-- Data Structures
-- Updated: {{DATE}}
--
-- Document your database schema, key models, and API contracts here.
-- This file serves as the source of truth for data structures.
--
-- Example:
-- CREATE TABLE users (
--   id UUID PRIMARY KEY,
--   email VARCHAR(255) NOT NULL UNIQUE,
--   created_at TIMESTAMP DEFAULT NOW()
-- );
